### ISSUE TITLE
Replace sqlops with azdata

### ISSUE THREAD

**Issue by KamasamaK** [dzsquared/sqlops-firstresponderkit#12]
Azure Data Studio is displaying the following warning:

The extension "drewsk.firstresponderkit" is using sqlops module which has been replaced by azdata module, the sqlops module will be removed in a future release.

**Comment by dzsquared** [comment]
Thanks for letting me know about the warning!  I will have the modules swapped out for the next release.

**Comment by dzsquared** [comment]
@KamasamaK this is corrected in v0.5.0, thanks!
