### ISSUE TITLE
Run sp_BlitzIndex from Context menu doesn't work properly

### ISSUE THREAD

**Issue by asharovarov** [dzsquared/sqlops-firstresponderkit#17]
Run sp_BlitzIndex from Context menu doesn't work properly in the latest version of the Azure Data Studio:

1. @DatabaseSchema parameter is missing for non-dbo objects
2. Doesn't support tables with "." in the name

**Comment by dzsquared** [comment]
Sorry I didn't close this back when the fix was merged in!
