### ISSUE TITLE
Where is vsix file available from 

### ISSUE THREAD

**Issue by talenyc** [dzsquared/sqlops-firstresponderkit#2]
I read through all the description but I can't find where is .vsix file available from 

Description of [readme ](https://github.com/dzsquared/sqlops-firstresponderkit) statesThe current release is available to download as a .vsix file and can be installed by opening the command palette (ctrl/command+shift+p) and selecting Extensions: Install from VSIX...

But it doesn't provide such a file in repository or external location.

**Comment by dzsquared** [comment]
@talenyc I'll add more detail and a direct download link to the readme before I close this issue, but I wanted to drop the link you need for the .vsix file here: https://github.com/dzsquared/sqlops-firstresponderkit/releases
