### ISSUE TITLE
Command 'First Responder Kit: Import sp_Blitz and all its friends' resulted in an error (404)

### ISSUE THREAD

**Issue by DigitalDuquette** [dzsquared/sqlops-firstresponderkit#29]
Following instructions on macOS (10.15.6) `First Responder Kit: Import sp_Blitz and all its friends` in command palette results in 404 error.  

![Screen Shot 2020-09-04 at 8 28 45 AM](https://user-images.githubusercontent.com/47231954/92239239-a89c4d00-ee88-11ea-92df-0539a073e97e.png)

Right-click on server and check version results in a loop of: 

![Screen Shot 2020-09-04 at 8 32 52 AM](https://user-images.githubusercontent.com/47231954/92239555-3a0bbf00-ee89-11ea-9448-9b320411b21b.png)

I'm not sure what the next steps are for trouble shooting.  Does this extension drop an error log somewhere?

**Comment by dzsquared** [comment]
**Thank you for raising an issue for the Azure Data Studio extension for the First Responder Kit!**

This isn't my full time job, but I hope to get back to you soon. I really appreciate feedback on issues and new feature requests!
        
If your question involves the First Responder Kit directly, you may find help in the [#FirstResponderKit Slack Channel](https://sqlcommunity.slack.com/messages/firstresponderkit/).

**Comment by dzsquared** [comment]
Hi @DigitalDuquette - unfortunately I'm behind on pushing out an update to the extension that resolves this issue. The issue is related to the change in branch naming across.  With the long weekend coming up I'll get back to you with an updated extension vsix to use.

**Comment by dzsquared** [comment]
@DigitalDuquette I've released an update to the extension, finally, and it should take care of this issue! 
https://github.com/dzsquared/sqlops-firstresponderkit/releases/tag/0.6.0
