### ISSUE TITLE
Use the master branch instead of dev branch

### ISSUE THREAD

**Issue by darshanrampatel** [dzsquared/sqlops-firstresponderkit#3]
Should't the `master` branch be used instead of the `dev` branch?

https://github.com/dzsquared/sqlops-firstresponderkit/blob/9f70af73b77622c89852604f4624c3c8a463061c/src/extension.ts#L8

**Comment by dzsquared** [comment]
Ah!  Good catch, you are correct.

**Comment by dzsquared** [comment]
v0.1.1 released addresses this, pull request open to post update to SQL Operations Studio
https://github.com/Microsoft/sqlopsstudio/pull/2412

@darshanrampatel you can download and install the vsix from here: https://github.com/dzsquared/sqlops-firstresponderkit/releases/tag/0.1.1
